# Generated by Django 2.2.2 on 2019-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, help_text='The About fields, where the user can provide some info about themselves.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="The User's avatar to be shown on their profile.", null=True, upload_to='images/avatars/'),
        ),
    ]
