dist: xenial
matrix:
  include:
    - language: python
      cache: pip
      python:
        - 3.7
      install:
        - python3 -m pip install -U -r backend/dev-requirements.txt
      script:
        - pytest backend/eatandmeet

    - language: node_js
      os: linux
      node_js:
        - node
      script:
        - npm install
        - npm test
        - npm run build
      notifications:
        email:
          recipients:
            - nitzan14@gmail.com
          on_success: never
          on_failure: always
