# Generated by Django 2.2.1 on 2019-05-24 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('Date', models.DateTimeField()),
                ('topics', models.CharField(choices=[('P', 'Politics'), ('S', 'Soccer')], max_length=1)),
                ('places', models.CharField(choices=[('M', 'Mathe mensa'), ('H', 'Hauptmensa')], default='H', max_length=1)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
