# Generated by Django 2.2.2 on 2019-07-10 00:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='SOME STRING', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('topics', multiselectfield.db.fields.MultiSelectField(choices=[('Politics', 'Politics'), ('Soccer', 'Soccer'), ('Films', 'Films'), ('Music', 'Music')], max_length=27)),
                ('places', models.CharField(choices=[('Mathe Mensa', 'Mathe Mensa'), ('Hauptmensa', 'Hauptmensa')], default='Hauptmensa', max_length=11)),
            ],
        ),
    ]
