# Generated by Django 2.2.2 on 2019-07-11 17:43

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='SOME STRING', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('topics', multiselectfield.db.fields.MultiSelectField(choices=[('Politics', 'Politics'), ('Education', 'Education'), ('Travel', 'Travel'), ('Sports', 'Sports'), ('Music', 'Music'), ('Movies', 'Movies'), ('Books', 'Books'), ('Technology', 'Technology'), ('Science', 'Science'), ('Animals', 'Animals'), ('Celebrities', 'Celebrities'), ('News', 'News'), ('General', 'General'), ('Smalltalk', 'Smalltalk')], max_length=113)),
                ('location', models.CharField(default='Hauptmensa', max_length=30)),
                ('slots', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('description', models.CharField(max_length=128)),
                ('day', models.DateField(blank=True)),
            ],
        ),
    ]
