# Generated by Django 2.2.1 on 2019-05-24 15:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Politics'), ('S', 'Soccer'), ('V', 'Video Games'), ('M', 'Music'), ('F', 'Films')], max_length=9),
        ),
    ]
