# Generated by Django 2.2.2 on 2019-07-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190710_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='places',
            new_name='location',
        ),
    ]
