# Generated by Django 2.2.2 on 2019-06-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20190613_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
        migrations.AddField(
            model_name='event',
            name='event_admins',
            field=models.ManyToManyField(null=True, related_name='event_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_members',
            field=models.ManyToManyField(null=True, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
