# Generated by Django 2.2.1 on 2019-05-24 18:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190524_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'Politics'), ('S', 'Soccer'), ('F', 'Films'), ('M', 'Music')], max_length=7),
        ),
    ]
