# Generated by Django 2.2.2 on 2019-07-11 17:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Politics', 'Politics'), ('Education', 'Education'), ('Travel', 'Travel'), ('Sports', 'Sports'), ('Music', 'Music'), ('Movies', 'Movies'), ('Books', 'Books'), ('Technology', 'Technology'), ('Science', 'Science'), ('Animals', 'Animals'), ('Celebrities', 'Celebrities'), ('News', 'News'), ('General', 'General'), ('Smalltalk', 'Smalltalk')], max_length=113),
        ),
    ]
