# Generated by Django 2.2.2 on 2019-07-10 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190710_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
