# Generated by Django 2.2.2 on 2019-06-13 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190613_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_admins',
            field=models.ManyToManyField(blank=True, related_name='event_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
