# Generated by Django 2.2.2 on 2019-06-13 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190613_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_members',
            field=models.ManyToManyField(blank=True, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
