export const FETCH_EVENT= 'FETCH_EVENT';
export const FETCH_EVENT_BEGIN = 'FETCH_EVENT_BEGIN';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';
export const TOGGLE_GOING = 'TOGGLE_GOING';
export const JOIN_EVENT = 'JOIN_EVENT';
export const LEAVE_EVENT = 'LEAVE_EVENT';
export const JOIN_EVENT_FAILURE = 'JOIN_EVENT_FAILURE';
export const LEAVE_EVENT_FAILURE = 'LEAVE_EVENT_FAILURE';

