export const FETCH_EVENT= 'FETCH_EVENT';
export const FETCH_EVENT_BEGIN = 'FETCH_EVENT_BEGIN';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_FAILURE = 'FETCH_EVENT_FAILURE';
export const TOGGLE_GOING = 'TOGGLE_GOING';
